version: 1
commandUpdated:
  generators:
    - command: kustomize build .
  updaters:
    # use https://github.com/squaremo/kubeyaml on flux-patch.yaml
    - containerImage:
        command: >-
          cat $FLUX_WL_NS/deployment.yaml | kubeyaml set --namespace $FLUX_WL_NS  --kind HelmRelease --name $FLUX_WL_NAME spec.values.staticImageTag=$FLUX_TAG spec.values.imageTag=${FLUX_TAG%.*} > new-flux-patch.yaml && mv new-flux-patch.yaml $FLUX_WL_NS/deployment.yaml
#          sed -i "s/^\(\s*imageTag\s*:\s*\).*/\1$MOJ_TAG/g" $FLUX_WL_NS/deployment.yaml
#          sed -i "s/^\(\s*staticImageTag\s*:\s*\).*/\1$FLUX_TAG/g" $FLUX_WL_NS/deployment.yaml
#
#      policy:
#        command: >-
#          cat flux-patch.yaml | kubeyaml annotate --namespace $FLUX_WL_NS --kind $FLUX_WL_KIND --name $FLUX_WL_NAME "fluxcd.io/$FLUX_POLICY=$FLUX_POLICY_VALUE" > new-flux-patch.yaml && mv new-flux-patch.yaml flux-patch.yaml
