---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: prod
spec:
  values:
    image:
      tag: prod-555
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stg
spec:
  values:
    image:
      tag: stg-231d1d
