---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:prod-*
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:1saikou/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: saikou/podinfo
      tag: prod-222
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
