---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-stg
  chart:
    git: git@github.com:1saikou/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: saikou/podinfo
      tag: stg-3
    replicaCount: 1
