---
staticServer:
  imagePullPolicy: IfNotPresent

  replicas: 1

internalIngress: {}
  # basicAuth: false
  # tls:
  # - hosts:
  #   - hostName
  #   secretName: secret

jmx: -Dcom.sun.management.jmxremote.authenticate=false
     -Dcom.sun.management.jmxremote.ssl=false
     -Dcom.sun.management.jmxremote.local.only=false
     -Dcom.sun.management.jmxremote.port=8887
     -Dcom.sun.management.jmxremote.rmi.port=8887
     -Djava.rmi.server.hostname=127.0.0.1

remoteDebug: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

namespace: required
imageTag: required
staticImageTag: required
customer: required
appProfile:
- production
hostName: required
useBetslipInternalAdress: true
enableDumper: "false"
deployOnlyStatic: false

## for add one number to the list starting on 2 for every node used...
multiNode: {}
# - "2"

nodeSelector: {}
  # node-spec.pbs.sw/os-family: linux
  # node-role.pbs.sw/worker: general
tolerations: {}
  # - effect: NoSchedule
  #   key: cattle.io/os
  #   operator: Equal
  #   value: linux