---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: <name>
  namespace: <namespace>
spec:
  chart:
    git: git@github.com:1saikou/helm-operator-get-started
    path: charts/podinfo
    ref: stg
  values:
    image:
      repository: saikou/podinfo
      tag: stg-2
    replicaCount: 1
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
